<?php
/**
 * This file was generated by Laravel Skeletons.
 * (c) 2025 László Kovács. Licensed under the MIT License.
 * Do not remove this header please!
 */
namespace App\Http\Controllers;

use App\Models\Studio;
use App\Http\Requests\StudioRequest;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use App\Helpers\ResponseHelper;

class StudioController extends Controller
{
    public function index(Request $request)
    {
        $needle = $request->get('needle');

        try {
            $url = $needle ? "studio?needle=" . urlencode($needle) : "studio";

            $response = Http::api()->get($url);

            if ($response->failed()) {
                $message = $response->json('message') ?? 'Ismeretlen hiba történt.';
                return redirect()
                    ->route('studios.index')
                    ->with('error', "Hiba történt a lekérdezés során: $message");
            }

            $entities = ResponseHelper::getData($response,'studios');
            /*var_dump($entities);
            die;*/

            return view('studio.index', ['studio' => $entities, 'isAuthenticated' => $this->isAuthenticated()]);

        } catch (\Exception $e) {
            return redirect()
                ->route('studios.index')
                ->with('error', "Nem sikerült betölteni a megyéket: " . $e->getMessage());
        }

    }

    public function show($id)
    {
        try {
            $response = Http::api()->get("/studio/$id");

            if ($response->failed()) {
                $message = $response->json('message') ?? 'A film nem található vagy hiba történt.';
                return redirect()
                    ->route('studio.index')
                    ->with('error', "Hiba: $message");
            }

            $body = $response->json();
            $entity = $body['studio'] ?? null;

            if (!$entity) {
                return redirect()
                    ->route('studio.index')
                    ->with('error', "A megye adatai nem érhetők el.");
            }

            return view('studio.show', ['entity' => $entity]);

        } catch (\Exception $e) {
            return redirect()
                ->route('studio.index')
                ->with('error', "Nem sikerült betölteni a megye adatait: " . $e->getMessage());
        }
    }

    public function create()
    {
        return view('studio.create');
    }
	

    public function store(StudioRequest $request)
    {
        $name = $request->get('name');

        try {
            $response = Http::api()
                ->withToken($this->token)
                ->post('/studio', ['name' => $name]);

            if ($response->failed()) {
                // Ha az API válaszolt, de hibás státuszkóddal (pl. 422, 403, 500)
                $message = $response->json('message') ?? 'Nem sikerült létrehozni a megyét.';
                return redirect()
                    ->route('studio.index')
                    ->with('error', "Hiba: $message");
            }

            return redirect()
                ->route('studio.index')
                ->with('success', "$name megye sikeresen létrehozva!");

        } catch (\Exception $e) {
            // Hálózati vagy JSON dekódolási hiba
            return redirect()
                ->route('studio.index')
                ->with('error', "Nem sikerült kommunikálni az API-val: " . $e->getMessage());
        }

    }

	public function edit($id)
    {
        try {
            $response = Http::api()->get("/studio/$id");

            if ($response->failed()) {
                $message = $response->json('message') ?? 'A megye nem található vagy hiba történt.';
                return redirect()
                    ->route('studio.index')
                    ->with('error', "Hiba: $message");
            }

            $body = $response->json();
            $entity = $body['Studio'] ?? null;

            if (!$entity) {
                return redirect()
                    ->route('studio.index')
                    ->with('error', "A megye adatai nem érhetők el.");
            }

            return view('studio.edit', ['entity' => $entity]);

        } catch (\Exception $e) {
            return redirect()
                ->route('studio.index')
                ->with('error', "Nem sikerült betölteni a megye szerkesztő nézetét: " . $e->getMessage());
        }
    }


    public function update(StudioRequest $request, $id)
    {
        $name = $request->get('name');

        try {
            $response = Http::api()
                ->withToken($this->token)
                ->put("/studio/$id", ['name' => $name]);

            if ($response->successful()) {
                return redirect()
                    ->route('studio.index')
                    ->with('success', "$name megye sikeresen frissítve!");
            }

            // Ha nem sikeres, de nem dobott kivételt (pl. 422)
            $errorMessage = $response->json('message') ?? 'Ismeretlen hiba történt.';
            return redirect()
                ->route('studio.index')
                ->with('error', "Hiba történt: $errorMessage");

        } catch (\Exception $e) {
            // Hálózati vagy egyéb kivétel
            return redirect()
                ->route('studio.index')
                ->with('error', "Nem sikerült frissíteni: " . $e->getMessage());
        }
    }


    public function destroy($id)
    {
        try {
            $response = Http::api()
                ->withToken($this->token)
                ->delete("/studio/$id", ['id' => $id]);

            if ($response->failed()) {
                $message = $response->json('message') ?? 'Nem sikerült törölni a megyét.';
                return redirect()
                    ->route('studio.index')
                    ->with('error', "Hiba: $message");
            }

            $body = $response->json();
            $name = $body['name'] ?? 'Ismeretlen';

            return redirect()
                ->route('studio.index')
                ->with('success', "$name megye sikeresen törölve!");

        } catch (\Exception $e) {
            return redirect()
                ->route('studio.index')
                ->with('error', "Nem sikerült kommunikálni az API-val: " . $e->getMessage());
        }
    }
}
